INSERT INTO car_models (make, model) VALUES
('Audi', 'A4'),
('Audi', 'A5'),
('Audi', 'A6'),
('Audi', 'A7'),
('Audi', 'Q3'),
('Audi', 'Q5'),
('Audi', 'Other'),
('BMW', '318'),
('BMW', '320'),
('BMW', '330'),
('BMW', '420'),
('BMW', '520'),
('BMW', '530'),
('BMW', '640'),
('BMW', 'X3'),
('BMW', 'X4'),
('BMW', 'Other'),
('Mercedes', 'A180'),
('Mercedes', 'B180'),
('Mercedes', 'C250'),
('Mercedes', 'CLA200'),
('Mercedes', 'CLS350'),
('Mercedes', 'E220'),
('Mercedes', 'GLE350'),
('Mercedes', 'Sprinter'),
('Mercedes', 'Vito'),
('Mercedes', 'Other'),
('Volkswagen', 'Amarok'),
('Volkswagen', 'Caddy'),
('Volkswagen', 'Crafter'),
('Volkswagen', 'Golf 5'),
('Volkswagen', 'Golf 6'),
('Volkswagen', 'Golf 7'),
('Volkswagen', 'Golf Plus'),
('Volkswagen', 'Jetta'),
('Volkswagen', 'Passat'),
('Volkswagen', 'Polo'),
('Volkswagen', 'Tiguan'),
('Volkswagen', 'Other'),
('Other', 'Other');